### ISSUE TITLE
Multiple destinations from same station

### ISSUE THREAD

**Issue by watercrossing** [jfparis/homeassistant_nationalrail#2]
I am interesting in multiple destinations from the same station, for example STP->WHP and STP->LTN. This causes the API to be called twice, once for STP-WHP and once for STP-LTN, even though the destinations are the same. I wonder if it is not easier to call the API once for all departures and then do the filtering afterwards? 
Also for trains that stop both at WHP and LTN, the destination is always set to WHP (https://github.com/jfparis/homeassistant_nationalrail/blob/b66e07b9977e5fe6122c12812529e81737da89c1/custom_components/nationalrailuk/client.py#L150). It would be good to expose the full list of calling points to home assistant.

**Comment by jfparis** [comment]
The destination is where I am going
What you want to look at is the "terminus" property for each of the trains. (this is what we use in the template)

On the one hand, National rail is very generous on its API quota. So double call is probably not a problem.
On the other hand, exposing the calling points would force the processing in the template and blow up the size of the returned data (impossible to read it via the developer tools). Easier to leave the work to sort slow and fast train to the API

**Comment by watercrossing** [comment]
![image](https://github.com/jfparis/homeassistant_nationalrail/assets/5656196/dc9d0157-3b1e-4502-bdb9-ec4e29ba5fa6)
The 5:22 train is listed twice. Once because it stops at KTN and once because it stops at STP. But for both trains it shows the arrival time for Kentish Town since the code above breaks at the first matching destination station.

I agree that this would cause more data to be stored in HA, but templates get evaluated serverside and filtering a couple of lists is not expensive.
I am also not sure why being able to read it via developer tools is important?

**Comment by watercrossing** [comment]
Ideally it would show something like
``` 
Sutton (London)       05:22 PM    05:22 PM   1
   Kentish Town                   05:52 PM  
   St Pancras Int                 05:57 PM
```

**Comment by jfparis** [comment]
I will have a look when I find some time. Having your station pair is very helpful. I should be able to have a quick fix for the first bug but I need to think harder for the callings

**Comment by watercrossing** [comment]
I managed to get it working last night, if I find some time tonight I will create a PR with the updated logic.

**Comment by jfparis** [comment]
Thank you @watercrossing
