### ISSUE TITLE
error - invalid API token

### ISSUE THREAD

**Issue by dharvey242** [jfparis/homeassistant_nationalrail#5]
I've recently had this in the log file and the result is no data appearing in the template.  Any ideas - 

`
data = await self.my_api.async_get_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nationalrailuk/client.py", line 199, in async_get_data
    raise NationalRailClientInvalidToken("Invalid API token") from err
custom_components.nationalrailuk.client.NationalRailClientInvalidToken: Invalid API token
`

**Comment by jfparis** [comment]
Your National Rail API token is invalid.

**Comment by dharvey242** [comment]
Do you have to re-register for another API token?  Does a link exist to see your API token/account?

**Comment by jfparis** [comment]
I have no idea. You might want to take this in the forum

**Comment by dharvey242** [comment]
In which file do you copy and paste the API token to?

**Comment by jfparis** [comment]
It is added via the configuration flow. No files need to be moditioned. I am going to log this bug. Further questions need to go in the home assistant forum
