### ISSUE TITLE
Add to HACS?

### ISSUE THREAD

**Issue by SpangleLabs** [jfparis/homeassistant_nationalrail#8]
This seems ultra helpful for the automations I'm eager to setup in Home Assistant, thank you so much for developing it!

Any chance you could add it to HACS, to ease installation and keeping it up to date? I spotted that's in the TODO list in the repo, but I figured I would add an issue too, and wondered if there's progress on that

**Comment by jfparis** [comment]
I have already added the HACS.json file so you should be able to install it that way (I don't use HACS)
