### ISSUE TITLE
limit rows in table?

### ISSUE THREAD

**Issue by wlinard** [jfparis/homeassistant_nationalrail#9]
I'm using your HTML code example, but it displays 10 rows. How can we limit this to say 5 of the next trains leaving?

**Comment by wlinard** [comment]
I added the following into the Style section. This only displays the 1st 3 rows:

tr:nth-child(n + 4) {visibility: hidden;}

But it's just hiding them, and the card size is too large:

<img width="915" alt="Screenshot 2024-02-01 at 20 46 40" src="https://github.com/jfparis/homeassistant_nationalrail/assets/96373434/13c84f2c-0107-4357-a3d2-99e81f48e1b9">

**Comment by jfparis** [comment]
Probably something you can resolve with some Jinja templates

https://jinja.palletsprojects.com/en/3.0.x/templates/#jinja-filters.first

Iterating over a range that is max (5, length(sensor)).
